### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by jaller94** [hobinjk/nineteen-below#1]
If this game is not exclusively uploaded for studying the code, it would be great if you could choose a license that allows sharing and distributing modified copies (alias forking).

Looking at your GitHub profile, you should be familiar with the process of choosing a license. If you need some inspiration have a look at choosealicense.com/. As long as you don't specify a license, one has to assume that you are the only one allowed to distribute the code and any modifications to it.

**Comment by hobinjk** [comment]
Thanks for pointing this out! I try to MIT license all of my personal projects but occasionally I forget. I've pushed an update accordingly.
